import time
i = 0
while i <= 100000:
    
    name = input("Enter your name: ")
    print ("")
    print ("Teacher : Helllo every body.")
    print ("")
    m = int(input("Say mam=1 sir=2: "))
    print ("")
    if (m==1):
        print (name,": Hello mam.")
        r = ("mam")
        print ("Teacher : How are you?")
        print ("")
        time.sleep(1)
        print ("")
        print (name,": We are fine and you?")
        time.sleep(3)
        print ("")
        print ("Teacher : Im allso fine.")
        time.sleep(2)
        print ("")
        print (name,": okay mam.")
        time.sleep(2)
        print ("")
        print ("Teacher :  What is the topic today?")
        time.sleep(2)
        print ("")
        topic = int(input("1 = My best Friend, 2 = My School. = "))
        if (topic==1):
            print (name,": My best Friend.")
            print ("")
            time.sleep(2)
            print ("Teacher : May I ask you some questions?")
            print ("")
            time.sleep(2)
            print (name,": Yes",r)
            print ("")
            time.sleep(1)
            friend = input("Teacher : Who is your Best Friend? = ")
            print ("")
            time.sleep(1)
            print (name,": My best friend name is:",friend,".")
            print ("")
            old = int(input("Teacher : how old is he. = "))
            print ("")
            time.sleep(1)
            print (name,": he is",old,"years old.")
            print ("")
            time.sleep(2)
            classs = int(input("Teacher : What class he read in? = "))
            print ("")
            time.sleep(1)
            print (name,": He reads in class",classs)
            time.sleep(2)
            lives = input("Teacher : Where does he live = ")
            print ("")
            time.sleep(1)
            print (name,": He live in",lives)
            print ("")
            time.sleep(1)
            print ("Teacher : How is he?")
            print ("")
            time.sleep(1)
            print (name,": He is very helpfull to me")
            print ("")
            time.sleep(2)
            print ("Teacher : Do you like him?")
            print ("")
            time.sleep(1)
            print (name,": Yes,I like him very much")
            print ("")
            time.sleep(2)
            print ("Teacher :  Okay,Thank you so much")
            print ("")
            time.sleep(2)
            print (name,": You are welcome")
            print ("")
            time.sleep(1)
            print ("End")
            print ("Craotor name is Tamim")
            break;
        elif(topic==2):
             print (name,": My School.")
             print ("")
             time.sleep(2)
             print ("Teacher : May I ask you some questions?")
             print ("")
             time.sleep(2)
             print (name,":Yes",r)
             print ("")
             time.sleep(1)
             school = input("Teacher : What is your school name? =")
             time.sleep(1)
             print ("")
             print (name,": My school name is",school)
             time.sleep(4)
             print ("")
             location = input("Teacher : where is it situated")
             time.sleep(4)
             print ("")
             print (name,": It is situated at",location)
             time.sleep(2)
             print ("")
             print ("Teacher : How was the school")
             time.sleep(1)
             print ("")
             print (name,": It is big and nice Academy School")
             time.sleep(2)
             print ("")
             many = int(input("Teacher : How many Student in your school? = "))
             time.sleep(1)
             print ("")
             print (name,": There about",many,"student in my school")
             print ("Teacher :  Okay,Thank you so much")
             print ("")
             time.sleep(2)
             print (name,": You are welcome")
             print ("")
             time.sleep(1)
             print ("End")
             print ("Craotor name is Tamim")
             break;
        else:
             print ("Sorry")
             i+=1
    elif(m==2):
         print (name,": Hello sir.")
         r = ("sir")
         print ("")
         print ("Teacher : How are you?")
         print ("")
         time.sleep(1)
         print ("")
         print (name,": We are fine and you?")
         time.sleep(3)
         print ("")
         print ("Teacher : Im allso fine.")
         time.sleep(2)
         print ("")
         print (name,": okay mam.")
         time.sleep(2)
         print ("")
         print ("Teacher :  What is the topic today?")
         time.sleep(2)
         print ("")
         topic = int(input("1 = My best Friend, 2 = My School. = "))
         if (topic==1):
             print (name,": My best Friend.")
             print ("")
             time.sleep(2)
             print ("Teacher : May I ask you some questions?")
             print ("")
             time.sleep(2)
             print (name,": Yes",r)
             print ("")
             time.sleep(1)
             friend = input("Teacher : Who is your Best Friend? = ")
             print ("")
             time.sleep(1)
             print (name,": My best friend name is:",friend,".")
             print ("")
             old = int(input("Teacher : how old is he. = "))
             print ("")
             time.sleep(1)
             print (name,": he is",old,"years old.")
             print ("")
             time.sleep(2)
             classs = int(input("Teacher : What class he read in? = "))
             print ("")
             time.sleep(1)
             print (name,": He reads in class",classs)
             time.sleep(2)
             print ("")
             lives = input("Teacher : Where does he live = ")
             print ("")
             time.sleep(1)
             print (name,": He live in",lives)
             print ("")
             time.sleep(1)
             print ("Teacher : How is he?")
             print ("")
             time.sleep(1)
             print (name,": He is very helpfull to me")
             print ("")
             time.sleep(2)
             print ("Teacher : Do you like him?")
             print ("")
             time.sleep(1)
             print (name,": Yes,I like him very much")
             print ("")
             time.sleep(2)
             print ("Teacher :  Okay,Thank you so much")
             print ("")
             time.sleep(2)
             print (name,": You are welcome")
             print ("")
             time.sleep(1)
             print ("End")
             print ("Craotor name is Tamim")
             break;
         elif(topic==2):
              print (name,": My School.")
              print ("")
              time.sleep(2)
              print ("Teacher : May I ask you some questions?")
              print ("")
              time.sleep(2)
              print (name,":Yes",r)
              print ("")
              time.sleep(1)
              school = input("Teacher : What is your school name? =")
              time.sleep(1)
              print ("")
              print (name,": My school name is",school)
              time.sleep(4)
              print ("")
              location = input("Teacher : where is it situated")
              time.sleep(4)
              print ("")
              print (name,": It is situated at",location)
              time.sleep(2)
              print ("")
              print ("Teacher : How was the school")
              time.sleep(1)
              print ("")
              print (name,": It is big and nice Academy School")
              time.sleep(2)
              print ("")
              many = int(input("Teacher : How many Student in your school? = "))
              time.sleep(1)
              print ("")
              print (name,": There about",many,"student in my school")
              print ("Teacher :  Okay,Thank you so much")
              print ("")
              time.sleep(2)
              print (name,": You are welcome")
              print ("")
              time.sleep(1)
              print ("End")
              print ("Craotor name is Tamim")
              break;
         else:
             print ("Sorry")
             i+=1
    else:
         print("sorry.")
         i+=1

