import time

i = 0
name = input("Enter your name: ")
print ("")
print ("Teacher : Helllo every body.")
print ("")
from tkinter import *
import colorsys
r = "mam"
def Mam():
     print ("mam")
     root.destroy()
def sir ():
     print ("Helo sir")
     root.destroy()
root = Tk()
root.geometry('430x430')
l = Label(root, text="Mam")
l.pack()
b = Button(root, text="Click Me", command=Mam)
b.pack()
i = Label (root, text="Sir")
i.pack()
c = Button (root, text="Click Me", command=sir)
c.pack()
root.mainloop()
print ("")
print ("TEACHER: How are you?")
print ("")
time.sleep(1)
print ("")
print (name,": We are fine and you?")
time.sleep(3)
print ("")
print ("Teacher : Im allso fine.")
time.sleep(2)
print ("")
print (name,": okay mam.")
time.sleep(2)
print ("")
print ("Teacher :  What is the topic today?")
time.sleep(2)
print ("")
def friendaa ():
     roota.destroy()
     print (name,": My best Friend.")
     print ("")
     time.sleep(2)
     print ("Teacher : May I ask you some questions?")
     print ("")
     time.sleep(2)
     print (name,": Yes",r)
     print ("")
     time.sleep(1)
     friend = input("Teacher : Who is your Best Friend? = ")
     print ("")
     time.sleep(1)
     print (name,": My best friend name is:",friend,".")
     print ("")
     old = int(input("Teacher : how old is he. = "))
     print ("")
     time.sleep(1)
     print (name,": he is",old,"years old.")
     print ("")
     time.sleep(2)
     classs = int(input("Teacher : What class he read in? = "))
     print ("")
     time.sleep(1)
     print (name,": He reads in class",classs)
     time.sleep(2)
     lives = input("Teacher : Where does he live = ")
     print ("")
     time.sleep(1)
     print (name,": He live in",lives)
     print ("")
     time.sleep(1)
     print ("Teacher : How is he?")
     print ("")
     time.sleep(1)
     print (name,": He is very helpfull to me")
     print ("")
     time.sleep(2)
     print ("Teacher : Do you like him?")
     print ("")
     time.sleep(1)
     print (name,": Yes,I like him very much")
     print ("")
     time.sleep(2)
     print ("Teacher :  Okay,Thank you so much")
     print ("")
     time.sleep(2)
     print (name,": You are welcome")
     print ("")
     time.sleep(1)
     print ("End")
     print ("Craotor name is Tamim")
def schooll():
     roota.destroy()
     print (name,": My School.")
     print ("")
     time.sleep(2)
     print ("Teacher : May I ask you some questions?")
     print ("")
     time.sleep(2)
     print (name,":Yes",r)
     print ("")
     time.sleep(1)
     school = input("Teacher : What is your school name? =")
     time.sleep(1)
     print ("")
     print (name,": My school name is",school)
     time.sleep(4)
     print ("")
     location = input("Teacher : where is it situated = ")
     time.sleep(4)
     print ("")
     print (name,": It is situated at",location)
     time.sleep(2)
     print ("")
     print ("Teacher : How was the school")
     time.sleep(1)
     print ("")
     print (name,": It is big and nice Academy School")
     time.sleep(2)
     print ("")
     many = int(input("Teacher : How many Student in your school? = "))
     time.sleep(1)
     print ("")
     print (name,": There about",many,"student in my school")
     print ("Teacher :  Okay,Thank you so much")
     print ("")
     time.sleep(2)
     print (name,": You are welcome")
     print ("")
     time.sleep(1)
     print ("End")
     print ("Craotor name is Tamim")
roota = Tk()
roota.geometry('400x400')
l = Label(roota, text="My School")
l.pack()
ba = Button(roota, text="Click Me", command=schooll)
ba.pack()
ia = Label (roota, text="My best Friend")
ia.pack()
ca = Button (roota, text="Click Me", command=friendaa)
ca.pack()
roota.mainloop()


import turtle as t
t.setup(width=600, height=600)
t.bgcolor("white")

# Draw the face (circle)
t.penup()
t.goto(0, -200)
t.pendown()
t.color("yellow")
t.begin_fill()
t.circle(200)
t.end_fill()

# Draw the eyes (circles)
def draw_eye(x, y):
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.color("black")
    t.begin_fill()
    t.circle(30)
    t.end_fill()

draw_eye(-70, 50)
draw_eye(70, 50)

# Draw the mouth (semicircle)
t.penup()
t.goto(-100, -50)
t.pendown()
t.color("black")
t.width(5)
t.setheading(-60)
t.circle(100, 120)

# Hide the turtle
t.hideturtle()

# Keep the window open until it's closed by the user
t.done()

     
